# Generated by Django 2.1.7 on 2019-03-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodname', models.CharField(max_length=200, null=True)),
                ('goodprice', models.BigIntegerField(null=True)),
                ('goodshop', models.CharField(max_length=200, null=True)),
                ('goodlink', models.URLField(max_length=1000, null=True)),
                ('goodimglink', models.URLField(max_length=1000, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='goodsdetail',
            name='goodtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchmenu.GoodsType'),
        ),
    ]
